export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'

export const BOARD_REQUEST = 'BOARD_REQUEST'
export const BOARD_SUCCESS = 'BOARD_SUCCESS'
export const BOARD_FAIL = 'BOARD_FAIL'

export const BOARD_CREATING_REQUEST = 'BOARD_CREATING_REQUEST'
export const BOARD_CREATING_SUCCESS = 'BOARD_CREATING_SUCCESS'
export const BOARD_CREATING_FAIL = 'BOARD_CREATING_FAIL'

export const TOKEN_KEY = 'fm_token'
export const SHOW_BOARD_CREATING = 'SHOW_BOARD_CREATING'
